# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hercules}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Diogo Biazus"]
  s.date = %q{2010-10-14}
  s.default_executable = %q{hercules}
  s.description = %q{Very simple deployment tool. It was made to deploy rails applications using github, bundler.}
  s.email = %q{diogob@gmail.com}
  s.executables = ["hercules"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/hercules",
     "hdi/README.md",
     "hdi/config.rb",
     "hdi/site/index.html",
     "hdi/site/stylesheets/style.css",
     "hdi/src/configuration.rb",
     "hdi/src/layouts/application.haml",
     "hdi/src/pages/_hdi.haml",
     "hdi/src/pages/_header.haml",
     "hdi/src/pages/_jquery.haml",
     "hdi/src/pages/index.haml",
     "hdi/src/stylesheets/style.sass",
     "hercules.gemspec",
     "lib/command_runner.rb",
     "lib/config.rb",
     "lib/deployer.rb",
     "lib/git_handler.rb",
     "lib/hercules.rb",
     "lib/http_handler.rb",
     "lib/request_handler.rb",
     "tests/command_runner_test.rb",
     "tests/config_test.rb",
     "tests/fixtures/Gemfile",
     "tests/fixtures/Gemfile.lock",
     "tests/fixtures/Gemfile.with_git_gem",
     "tests/fixtures/Gemfile.with_git_gem.lock",
     "tests/fixtures/bogus_config.yml",
     "tests/fixtures/bogus_deployer.rb",
     "tests/fixtures/config.yml",
     "tests/fixtures/config_empty.yml",
     "tests/fixtures/config_empty_branches.yml",
     "tests/fixtures/config_empty_projects.yml",
     "tests/fixtures/config_global.yml",
     "tests/fixtures/config_partial_1.yml",
     "tests/fixtures/config_partial_2.yml",
     "tests/fixtures/config_partial_3.yml",
     "tests/fixtures/deployer_branch.rb",
     "tests/fixtures/deployer_exception.rb",
     "tests/fixtures/deployer_false.rb",
     "tests/fixtures/deployer_path.rb",
     "tests/fixtures/deployer_true.rb",
     "tests/fixtures/deployer_undefined_variable.rb",
     "tests/fixtures/startup_checkout_config.yml",
     "tests/fixtures/startup_checkout_error_config.yml",
     "tests/git_handler_test.rb",
     "tests/git_setup.rb",
     "tests/hercules_test.rb",
     "tests/http_handler_test.rb",
     "tests/request_handler_test.rb",
     "tests/startup.rb"
  ]
  s.homepage = %q{http://github.com/diogob/hercules}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple deploy solution for ruby applications (using github+bundler).}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, ["= 0.12.10"])
      s.add_runtime_dependency(%q<eventmachine_httpserver>, ["= 0.2.0"])
      s.add_runtime_dependency(%q<git>, ["= 1.2.5"])
      s.add_runtime_dependency(%q<json>, ["= 1.4.6"])
      s.add_runtime_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<haml>, ["= 3.0.18"])
      s.add_development_dependency(%q<compass>, ["= 0.10.5"])
      s.add_development_dependency(%q<staticmatic>, ["= 0.10.8"])
    else
      s.add_dependency(%q<eventmachine>, ["= 0.12.10"])
      s.add_dependency(%q<eventmachine_httpserver>, ["= 0.2.0"])
      s.add_dependency(%q<git>, ["= 1.2.5"])
      s.add_dependency(%q<json>, ["= 1.4.6"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<haml>, ["= 3.0.18"])
      s.add_dependency(%q<compass>, ["= 0.10.5"])
      s.add_dependency(%q<staticmatic>, ["= 0.10.8"])
    end
  else
    s.add_dependency(%q<eventmachine>, ["= 0.12.10"])
    s.add_dependency(%q<eventmachine_httpserver>, ["= 0.2.0"])
    s.add_dependency(%q<git>, ["= 1.2.5"])
    s.add_dependency(%q<json>, ["= 1.4.6"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<haml>, ["= 3.0.18"])
    s.add_dependency(%q<compass>, ["= 0.10.5"])
    s.add_dependency(%q<staticmatic>, ["= 0.10.8"])
  end
end

